apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitworks-workbench-storage-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "standard"
  volumeName: gitworks-workbench-storage
  resources:
    requests:
      storage: 25Gi